# Generated by Django 5.2.17 on 2026-08-30 09:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_alt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alt. Phone')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='PAN/VAT Number')),
                ('vat_registered', models.BooleanField(default=False, verbose_name='VAT Registered')),
                ('contact_type', models.CharField(choices=[('Customer', 'Customer'), ('Supplier', 'Supplier'), ('Both', 'Both')], default='Customer', max_length=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Item Code')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('Goods', 'Goods'), ('Service', 'Service')], default='Goods', max_length=10)),
                ('unit', models.CharField(choices=[('Pcs', 'Pcs'), ('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Box', 'Box'), ('Doz', 'Dozen'), ('Mtr', 'Meter'), ('Set', 'Set'), ('Pair', 'Pair'), ('Other', 'Other')], default='Pcs', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Online', 'Online')], default='Cash', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('15 Days', '15 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days')], default='Immediate', max_length=20)),
                ('sales_type', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services'), ('Mixed', 'Mixed')], default='Goods', max_length=20)),
                ('sale_category', models.CharField(choices=[('Local Sales', 'Local Sales'), ('Export', 'Export'), ('Government', 'Government')], default='Local Sales', max_length=20)),
                ('vat_treatment', models.CharField(choices=[('With VAT (13%)', 'With VAT (13%)'), ('Non VAT', 'Non VAT'), ('Zero Rated', 'Zero Rated')], default='With VAT (13%)', max_length=20)),
                ('currency', models.CharField(choices=[('NPR', 'NPR'), ('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR')], default='NPR', max_length=5)),
                ('subtotal_taxable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal_non_taxable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='VAT Amount')),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('terms_conditions', models.TextField(blank=True, default='Thank you for your business.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'contact_type__in': ['Customer', 'Both']}, on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('Mobile Banking', 'Mobile Banking')], default='Cash', max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Unallocated', 'Unallocated'), ('Partially Allocated', 'Partially Allocated'), ('Fully Allocated', 'Fully Allocated')], default='Unallocated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'contact_type__in': ['Customer', 'Both']}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.contact')),
                ('invoice', models.ForeignKey(blank=True, help_text='The new invoice this payment was received with (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_payments', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('basis', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], default='Percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.customerpayment')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(default='Pcs', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('is_return', models.BooleanField(default=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], default='Fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_type', models.CharField(choices=[('Taxable', 'Taxable'), ('Non-Tax', 'Non-Tax'), ('Zero Rated', 'Zero Rated')], default='Taxable', max_length=20)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=13.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productcategory'),
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='VAT Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('supplier', models.ForeignKey(limit_choices_to={'contact_type__in': ['Supplier', 'Both']}, on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchasebill')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('refund_method', models.CharField(choices=[('Adjust in Next Invoice', 'Adjust in Next Invoice'), ('Refund to Customer', 'Refund to Customer'), ('Credit Note', 'Credit Note')], default='Adjust in Next Invoice', max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Adjusted', 'Adjusted'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'contact_type__in': ['Customer', 'Both']}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='core.contact')),
                ('original_invoice', models.ForeignKey(blank=True, help_text='The original sale this return is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(default='Pcs', max_length=20)),
                ('returned_qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_type', models.CharField(choices=[('Taxable', 'Taxable'), ('Non-Tax', 'Non-Tax'), ('Zero Rated', 'Zero Rated')], default='Taxable', max_length=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesreturn')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('Online', 'Online')], default='Cash', max_length=20)),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.purchasebill')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_margins', models.BooleanField(default=False)),
                ('can_view_cost', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
