# Generated by Django 4.2.30 on 2026-09-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quotation_salesreturnitem_disposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat_treatment',
            field=models.CharField(choices=[('Standard', 'Standard (13%)'), ('Zero Rated', 'Zero Rated (0%)'), ('Exempt', 'Exempt (No VAT)')], default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax_type',
            field=models.CharField(choices=[('Standard', 'Standard (13%)'), ('Zero Rated', 'Zero Rated (0%)'), ('Exempt', 'Exempt (No VAT)')], default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='tax_type',
            field=models.CharField(choices=[('Standard', 'Standard (13%)'), ('Zero Rated', 'Zero Rated (0%)'), ('Exempt', 'Exempt (No VAT)')], default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='tax_type',
            field=models.CharField(choices=[('Standard', 'Standard (13%)'), ('Zero Rated', 'Zero Rated (0%)'), ('Exempt', 'Exempt (No VAT)')], default='Standard', max_length=20),
        ),
    ]
