# Generated by Django 4.2.30 on 2026-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_invoice_vat_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_attachment',
            field=models.FileField(blank=True, null=True, upload_to='invoices/attachments/'),
        ),
    ]
