# Generated by Django 4.2.30 on 2026-09-08 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_invoice_bill_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/receipts/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.FloatField(default=0.0, verbose_name='Size (MB)')),
                ('description', models.TextField(blank=True, null=True)),
                ('label', models.CharField(choices=[('UNLABELED', 'Add Label'), ('INVOICE', 'Sales Invoice'), ('PURCHASE', 'Purchase Bill'), ('EXPENSE', 'Expense'), ('PAYMENT', 'Payment')], default='UNLABELED', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_receipt_documents', to='core.invoice')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
