# Generated by Django 4.2.30 on 2026-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_receiptdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='hs_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HS Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System Code for customs/tax classification', max_length=20, null=True, verbose_name='HS Code'),
        ),
    ]
