# Generated by Django 4.2.30 on 2026-09-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoiceitem_hs_code_product_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='bill_attachment',
            field=models.FileField(blank=True, null=True, upload_to='sales_returns/attachments/'),
        ),
    ]
