# Generated by Django 4.2.30 on 2026-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_salesreturn_bill_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pan_type',
            field=models.CharField(choices=[('PAN', 'PAN'), ('VAT', 'VAT')], default='PAN', max_length=10, verbose_name='PAN/VAT Type'),
        ),
    ]
