# Generated by Django 4.2.30 on 2026-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_salesorder_invoice_quotation_alter_quotation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHelpGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(help_text='Unique key for the page', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes/instructions for this page', null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video link tutorial for this page', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
