# Generated by Django 4.2.30 on 2026-09-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pagehelpguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(default='General Note', max_length=255)),
                ('content', models.TextField(help_text='Content of the note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageVideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(default='Video Tutorial', max_length=255)),
                ('video_url', models.URLField(help_text='YouTube or video link tutorial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
