# Generated by Django 4.2.30 on 2026-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_billattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='cheque_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='is_pdc',
            field=models.BooleanField(default=False, help_text='Is this a Post-Dated Cheque?'),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='pdc_status',
            field=models.CharField(blank=True, choices=[('Pending Clearance', 'Pending Clearance'), ('Cleared', 'Cleared'), ('Bounced', 'Bounced'), ('Cancelled', 'Cancelled')], default='Cleared', max_length=20, null=True),
        ),
    ]
