# Generated by Django 4.2.30 on 2026-09-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customerpayment_cheque_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='is_pdc',
            field=models.BooleanField(default=False, help_text='Is this a Post-Dated Cheque?'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='pdc_status',
            field=models.CharField(blank=True, choices=[('Pending Clearance', 'Pending Clearance'), ('Cleared', 'Cleared'), ('Bounced', 'Bounced'), ('Cancelled', 'Cancelled')], default='Cleared', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('PDC Pending', 'PDC Pending')], default='Draft', max_length=20),
        ),
    ]
