# Generated by Django 4.2.30 on 2026-09-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_supplierpayment_cheque_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=150, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bank_name', 'account_number'],
            },
        ),
    ]
