# Generated by Django 4.2.30 on 2026-09-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customer_category',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('One-Time', 'One-Time'), ('Walk-In', 'Walk-In'), ('Corporate', 'Corporate'), ('VIP', 'VIP'), ('Wholesale', 'Wholesale')], default='Regular', max_length=20, null=True, verbose_name='Customer Type'),
        ),
    ]
