from django.urls import path
from .views import (
    HomeView,
    SalesView,
    CustomerView,
    CustomerAddView,
    InvoiceView,
    CustomerPaymentView,
    CustomersView,
    InventoryView,
    PurchaseView,
    PurchaseAddView,
    ExpensesView,
    ExpensesAddView,
    SupplierPaymentView,
    SupplierAddView,
    InventoryProductView,
    InvoiceAddView,
    CustomerPaymentAddView,
    VariantProductView,
    VariantProductAddView,
    VariantAttributeView,
    ProductCategoryView,
    UnitsMeasurementView,
    WarehouseTransferView,
    WarehouseAddView,
    InventoryAdjustmentView,
    InventoryAdjustAddView,
    BillMaterialView,
    BillMaterialAddView,
    ProductionOrderView,
    ProductionJournalView,
    SupplierPaymentAddView,
    UnpaidInvoicesJsonView,
    UnpaidPurchaseBillsJsonView,
    ProductionOrderAddView,
    ProductionJournalAddView,
)
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("sales/", SalesView.as_view(), name="sales"),
    path("sales/customers/", CustomerView.as_view(), name="customers"),
    path("sales/customers/add/", CustomerAddView.as_view(), name="customer_add"),
    path("sales/invoice/",InvoiceView.as_view(),name="invoice"),
    path("sales/customer-payment/",CustomerPaymentView.as_view(),name="customer_payment"),  
    path("sales/customers/",CustomersView.as_view(),name="customers"),  
    path("inventory/",InventoryView.as_view(),name="inventory"),
    path("inventory/product/",InventoryProductView.as_view(),name="inventory_product"),
    path("sales/invoice/add/", InvoiceAddView.as_view(), name="invoice_add"),
    path("sales/customer-payment/add/",CustomerPaymentAddView.as_view(),name="customer_payment_add"),
    path("purchase/",PurchaseView.as_view(),name="purchase"),
    path("purchase/add/",PurchaseAddView.as_view(),name="purchase_add"),
    path("purchase/expenses/", ExpensesView.as_view(), name="expenses"),
    path("purchase/expenses/add/", ExpensesAddView.as_view(), name="expenses_add"),
    path("purchase/supplier-payment/",SupplierPaymentView.as_view(),name="supplier_payment"),
    path('purchase/supplier-payment/add/', SupplierPaymentAddView.as_view(), name='supplier_payment_add'),
    path('purchase/supplier_add/', SupplierAddView.as_view(), name='supplier_add'),
    path('api/unpaid-invoices/<int:customer_id>/', UnpaidInvoicesJsonView.as_view(), name='unpaid_invoices_json'),
    path('api/unpaid-bills/<int:supplier_id>/', UnpaidPurchaseBillsJsonView.as_view(), name='unpaid_bills_json'),
    path("inventory/variant-product/",VariantProductView.as_view(),name="variant_product"),
    path("inventory/variant-product/add/",VariantProductAddView.as_view(),name="variant_product_add"),
    path("inventory/variant-attribute/",VariantAttributeView.as_view(),name="variant_attribute"),
    path("inventory/product-category/",ProductCategoryView.as_view(),name="product_category"),
    path("inventory/units-measurement/",UnitsMeasurementView.as_view(),name="units_measurement"),
    path("inventory/warehouse-transfer/",WarehouseTransferView.as_view(),name="warehouse_transfer"),
    path("inventory/warehouse-transfer/add/",WarehouseAddView.as_view(),name="warehouse_add"),
    path("inventory/inventory-adjustment/",InventoryAdjustmentView.as_view(),name="inventory_adjustment"),
    path("inventory/inventory-adjustment/add/",InventoryAdjustAddView.as_view(),name="inventory_adjust_add"),
    path("inventory/bill-material/",BillMaterialView.as_view(),name="bill_material"),
    path("inventory/bill-material/add",BillMaterialAddView.as_view(),name="bill_material_add"),
    path("inventory/production-order/",ProductionOrderView.as_view(),name="production_order"),
    path("inventory/production-order/add/",ProductionOrderAddView.as_view(),name="production_order_add"),
    path("inventory/production-journal/",ProductionJournalView.as_view(),name="production_journal"),
    path("inventory/production-journal/add/",ProductionJournalAddView.as_view(),name="production_journal_add"),
]