from django.urls import path
from .views import (
    HomeView,
    SalesView,
    InvoiceView,
    CustomerPaymentView,
    InventoryView,
    PurchaseView,
    PurchaseAddView,
    ExpensesView,
    ExpensesAddView,
    SupplierPaymentView,
    SupplierAddView,
    InventoryProductView,
    InvoiceAddView,
    CustomerPaymentAddView,
    VariantProductView,
    VariantAttributeView,
    ProductCategoryView,
    WarehouseTransferView,
    InventoryAdjustmentView,
    BillMaterialView,
    ProductionOrderView,
    ProductionJournalView
)
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("sales/", SalesView.as_view(), name="sales"),
    path("sales/invoice/",InvoiceView.as_view(),name="invoice"),
    path("sales/customer-payment/",CustomerPaymentView.as_view(),name="customer_payment"),  
    path("inventory/",InventoryView.as_view(),name="inventory"),
    path("inventory/product/",InventoryProductView.as_view(),name="inventory_product"),
    path("sales/invoice/add/", InvoiceAddView.as_view(), name="invoice_add"),
    path("sales/customer-payment/add/",CustomerPaymentAddView.as_view(),name="customer_payment_add"),
    path("purchase/",PurchaseView.as_view(),name="purchase"),
    path("purchase/add/",PurchaseAddView.as_view(),name="purchase_add"),
    path("purchase/expenses/", ExpensesView.as_view(), name="expenses"),
    path("purchase/expenses/add/", ExpensesAddView.as_view(), name="expenses_add"),
    path("purchase/supplier-payment/",SupplierPaymentView.as_view(),name="supplier_payment"),
    path("purchase/supplier_add.html/",SupplierAddView.as_view(),name="supplier_add"),
    path("inventory/variant-product/",VariantProductView.as_view(),name="variant_product"),
    path("inventory/variant-attribute/",VariantAttributeView.as_view(),name="variant_attribute"),
    path("inventory/product-category/",ProductCategoryView.as_view(),name="product_category"),
    path("inventory/warehouse-transfer/",WarehouseTransferView.as_view(),name="warehouse_transfer"),
    path("inventory/inventory-adjustment/",InventoryAdjustmentView.as_view(),name="inventory_adjustment"),
    path("inventory/bill-material/",BillMaterialView.as_view(),name="bill_material"),
    path("inventory/production-order/",ProductionOrderView.as_view(),name="production_order"),
    path("inventory/production-journal/",ProductionJournalView.as_view(),name="production_journal"),

]